### ISSUE TITLE
What happend to Nuym's JNIC

### ISSUE THREAD

**Issue by micartey** [nuym/j2c#1]
Link is broken and project is gone/private or got taken down

**Comment by nuym** [comment]
> Link is broken and project is gone/private or got taken down

My JNIC was DMCA. The reason is because I used jnic.dev's official website and violated the copyright. So I am going to reopen the library and rename it, but the code is pretty bad, so I am trying to figure out when to fix it and open source it. If you are eager to need it, please contact my discord: .nuym

**Comment by micartey** [comment]
So you are saying konsolas took down JNIC while being gone since half a year and not responding to his community?

**Comment by nuym** [comment]
sry，wdym,I just started school, tomorrow afternoon I will sort out the code to re-open source, the code may be a little bad, I hope you do not mind, I also noticed that you have restarted your anti-cheating project, can I test it?
use wechat translate

**Comment by nuym** [comment]
Well, I pushed it up and thank you for your support.
